
export const LOGIN_USER = 'LOGIN_USER';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';
export const MEAL_LIST = 'MEAL_LIST'
export const NO_MEALS = 'NO_MEALS'
export const MAKE_ORDER = 'MAKE_ORDER'
export const MAKE_ORDER_FAILED = 'MAKE_ORDER_FAILED'
export const ORDERS_LIST = 'ORDERS_LIST'
export const NO_ORDERS = 'NO_ORDERS'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const UPDATE_ORDER_FAILED = 'UPDATE_ORDER_FAILED'
export const DELETE_ORDER = 'DELETE_ORDER'
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED'
